<a href="https://colab.research.google.com/github/25wh1a05w4-abc/NASSCOM-LAB/blob/main/Untitled3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
u=np.array([2,3])
v=np.array([4,1])
print("u+v=",u+v)
print("3*u=",3*u)

u+v= [6 4]
3*u= [6 9]


In [ ]:
import numpy as np
Maths=np.array([30,29,28,27])
Science=np.array([25,26,27,28])
English=np.array([27,26,28,25])
print("Maths: ",Maths)
print("Science: ",Science)
print("English: ",English)
print("Maths+English=",Maths+English)
print("Maths+Science=",Maths+Science)
print("English+Science=",English+Science)
print("Maths+Science+English=",Maths+Science+English)

Maths:  [30 29 28 27]
Science:  [25 26 27 28]
English:  [27 26 28 25]
Maths+English= [57 55 56 52]
Maths+Science= [55 55 55 55]
English+Science= [52 52 55 53]
Maths+Science+English= [82 81 83 80]


In [ ]:
import numpy as np
A=np.array([[9,9],[9,9]])
B=np.array([[1,4],[2,5]])
print("A+B=\n",A+B)
print("A-B=\n",A-B)
print("A*B=\n",A*B)
print("A/B=\n",A/B)
print("A@B=\n",A@B)

A+B=
 [[10 13]
 [11 14]]
A-B=
 [[8 5]
 [7 4]]
A*B=
 [[ 9 36]
 [18 45]]
A/B=
 [[9.   2.25]
 [4.5  1.8 ]]
A@B=
 [[27 81]
 [27 81]]


In [ ]:
i=np.eye(3)
print("")